import "./assets/main.scss";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createPinia } from "pinia";
import { createPersistedState } from "pinia-persistedstate-plugin";
import locale from "element-plus/dist/locale/zh-cn.js";
const pinia = createPinia();
const persist = createPersistedState();
const app = createApp(App);
pinia.use(persist);
app.use(ElementPlus, { locale });
app.use(router);
app.use(pinia);
app.mount("#app");
